// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSLink } from "./TSLink";

export type Session = { _id: string, created: string, last_connection: string, user: TSLink, };
