// This file is auto-generated by @hey-api/openapi-ts

import type { GetIndexResponse } from './types.gen';

const sessionSchemaResponseTransformer = (data: any) => {
    data.created = new Date(data.created);
    data.last_connection = new Date(data.last_connection);
    return data;
};

const indexInfoSchemaResponseTransformer = (data: any) => {
    data.session = sessionSchemaResponseTransformer(data.session);
    return data;
};

export const getIndexResponseTransformer = async (data: any): Promise<GetIndexResponse> => {
    data = indexInfoSchemaResponseTransformer(data);
    return data;
};