// This file is auto-generated by @hey-api/openapi-ts

export type IndexInfo = {
    session: Session;
    runner_mode: RunnerMode;
};

export type Session = {
    _id?: string;
    created: string;
    last_connection: string;
    user?: TsLink | null;
};

export type TsLink = {
    collection: string;
    id: string;
};

export type RunnerMode = 'docker_host';

export type RedactedUser = {
    id: string;
    username: string;
    superuser: boolean;
};

export type LoginModel = {
    username: string;
    password: string;
};

export type GetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetIndexResponses = {
    200: IndexInfo;
};

export type GetIndexResponse = GetIndexResponses[keyof GetIndexResponses];

export type LoginData = {
    body: LoginModel;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * # [Error 400](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400)
     * An error occurred while trying to parse the user's request.
     */
    400: unknown;
    /**
     * # [Error 404](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404)
     * Requested resource not found
     */
    404: unknown;
    /**
     * # [Error 500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500)
     * Internal server error occurred while processing request.
     */
    500: unknown;
};

export type LoginResponses = {
    200: RedactedUser;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type ClientOptions = {
    baseURL: 'https://0.0.0.0:8000' | (string & {});
};