// This file is auto-generated by @hey-api/openapi-ts

export type RedactedUser = {
    id: string;
    username: string;
};

export type LoginModel = {
    username: string;
    password: string;
};

export type LoginData = {
    body: LoginModel;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * # [Error 400](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400)
     * An error occurred while trying to parse the user's request.
     */
    400: unknown;
    /**
     * # [Error 404](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404)
     * Requested resource not found
     */
    404: unknown;
    /**
     * # [Error 500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500)
     * Internal server error occurred while processing request.
     */
    500: unknown;
};

export type LoginResponses = {
    200: RedactedUser;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type ClientOptions = {
    baseURL: 'https://0.0.0.0:8000' | (string & {});
};